version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: employees
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./mysql/test-dump.sql:/docker-entrypoint-initdb.d/test-dump.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./nodejs
    depends_on:
      - mysql
    expose:
      - 8001
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: employees
      MYSQL_HOST_IP: mysql
    ports:
      - 8001:8001
    volumes:
      - ./nodejs:/app
    links:
      - mysql
    command: npm run prod
